### ISSUE TITLE
Remove <h3> from premable.xhtml

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/nikolai-vasilievich-gogol_dead-souls#9]
I think we can remove `<h3>Second Edition published in 1846</h3>` entirely.  I'm not sure why that information is relevant to the preamble; and either way, `<h#>` tags are for section titles that should appear in the ToC, and this one shouldn't.

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/robinwhittleton/nikolai-vasilievich-gogol_dead-souls/commit/f977eeb37925a3b74fdd74d224435d58bd27c702
